config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'
  resources :pastes
  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/search' => 'pastes#search', as: "search"
  delete '/deletepaste/:id'=>'pastes#destroyredirect', as:"destroyredirect"
  root 'homepage#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/paste.rb
class Paste < ApplicationRecord

	#guests able to create pastess
	belongs_to :user, optional: true

	after_initialize :init

	def init
		if content.present? && title.blank?
			self.title = "untitled"
		end
	end


	def self.search(params = {}) 
		if params[:search].present?
			return search_results(params[:search])
		else
			return self.all.order(created_at: :desc)
		end
	end


scope :search_results, ->(search) { where('content LIKE ? or title LIKE ?', "%#{search}%","%#{search}%") }

end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates_uniqueness_of :username
	validates_uniqueness_of :email
	validates :username, :password, :email, presence: true


	has_many :pastes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :current_user, :logged_in?, :sign_out
	def current_user
		if session[:user_id]
			@current_user ||= User.find(session[:user_id])
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def sign_in(user)
		session[:user_id] = user.id
	end

	def sign_out
		session[:current_user_id] = nil
	end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/pastes_controller.rb
class PastesController < ApplicationController

	before_action :check_update_rights, only: [:update, :destroy]
	def index
		@pastes = Paste.search(params).page(params[:page]).per(10).all
	end

	def new
		@paste = Paste.new
	end

	def show
		@paste = Paste.find(params[:id])
	end

	def create
		@paste = Paste.new(paste_params)
		# If user signed in, save the user id into the paste
		if logged_in?
			@paste.user = current_user
		end

		if @paste.save
			redirect_to pastes_path
		else
			redirect_back(fallback_location: 'root')
		end

	end

	def destroy
		@paste = Paste.find(params[:id])
		@paste.destroy
		respond_to do |format|
			format.js
		end
	end

	def destroyredirect
		@paste = Paste.find(params[:id])
		@paste.destroy
		redirect_to pastes_path
	end

	def edit
		@paste = Paste.find(params[:id])
	end

	def update
	@paste = Paste.find(params[:id])
		if @paste.update(paste_params)
      		redirect_to @paste
    	else
      		render 'edit'
    	end
	end


	private
	#whitelist params
	def paste_params
		params.require(:paste).permit(:title, :content)
	end

	def check_update_rights
		@paste = Paste.find(params[:id])
		if current_user.id != @paste.user_id && !current_user.admin?
			flash[:denied] = "Access denied!"
			redirect_to pastes_path
		end
	end

	def search_params
		params.require(:search).permit(:search)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.find_by(username:params[:username])
	# If the user exists and the password entered is correct
		if user && user.authenticate(params[:password])
			#Save the user id inside the browser cookie.
			session[:user_id]  = user.id
			redirect_to '/'
		else
			#Redirect back to login form
			redirect_to '/login'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/login'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		# if @user.save
		# 	session[:user_id] = @user.id
		# 	redirect_to '/'
		# else
		# 	redirect_back(fallback_location: 'root')
		# end
		if !verify_recaptcha(model: @user) || !@user.save
      		render "new"
      	else
      		redirect_to '/'
    	end
	end



	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/pastes_helper.rb
module PastesHelper
	def current_user
		if session[:user_id]
			@current_user ||= User.find(session[:user_id])
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def sign_in(user)
		session[:user_id] = user.id
	end

	def sign_out
		session[:current_user_id] = nil
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homepage/index.html.erb
<link href='https://fonts.googleapis.com/css?family=Noto+Serif:700,700italic' rel='stylesheet' type='text/css'>
<h1 style="text-align:center">Welcome to Atlas!</h1>
<canvas></canvas>
<!-- Style from https://codepen.io/gbnikolov/pen/jEqQdG -->
<style>
clear: * {
  margin: 0;
  padding: 0;
}

canvas {
  display: block;
}
</style>

<script>

 var particleAlphabet = {

    Particle: function(x, y) {
        this.x = x;
        this.y = y;
        this.radius = 3.5;
        this.draw = function(ctx) {
            ctx.save();
            ctx.translate(this.x, this.y);
            ctx.fillStyle = "white";
            ctx.fillRect(0, 0, this.radius, this.radius);
            ctx.restore();
        };
    },
    init: function() {
        particleAlphabet.canvas = document.querySelector('canvas');
        particleAlphabet.ctx = particleAlphabet.canvas.getContext('2d');
        particleAlphabet.W = window.innerWidth;
        particleAlphabet.H = window.innerHeight;
        particleAlphabet.particlePositions = [];
        particleAlphabet.particles = [];
        particleAlphabet.tmpCanvas = document.createElement('canvas');
        particleAlphabet.tmpCtx = particleAlphabet.tmpCanvas.getContext('2d');

        particleAlphabet.canvas.width = particleAlphabet.W;
        particleAlphabet.canvas.height = particleAlphabet.H;

        setInterval(function(){
            particleAlphabet.changeLetter();
            particleAlphabet.getPixels(particleAlphabet.tmpCanvas, particleAlphabet.tmpCtx);
        }, 1200);

        particleAlphabet.makeParticles(3000);
        particleAlphabet.animate();
    }, 
    currentPos: 0,
    changeLetter: function() {
        var letters = 'Copy,Paste,Share',
            letters = letters.split(',');
        particleAlphabet.time = letters[particleAlphabet.currentPos];
        particleAlphabet.currentPos++;
        if (particleAlphabet.currentPos >= letters.length) {
            particleAlphabet.currentPos = 0;
        }
    },
    makeParticles: function(num) {
        for (var i = 0; i <= num; i++) {
            particleAlphabet.particles.push(new particleAlphabet.Particle(particleAlphabet.W / 2 + Math.random() * 400 - 200, particleAlphabet.H / 2 + Math.random() * 400 -200));
        }
    },
    getPixels: function(canvas, ctx) {
        var keyword = particleAlphabet.time,
            gridX = 6,
            gridY = 6;
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
        ctx.fillStyle = 'red';
        ctx.font = 'italic bold 330px Noto Serif';
        ctx.fillText(keyword, canvas.width / 2 - ctx.measureText(keyword).width / 2, canvas.height / 2 + 100);
        var idata = ctx.getImageData(0, 0, canvas.width, canvas.height);
        var buffer32 = new Uint32Array(idata.data.buffer);
        if (particleAlphabet.particlePositions.length > 0) particleAlphabet.particlePositions = [];
        for (var y = 0; y < canvas.height; y += gridY) {
            for (var x = 0; x < canvas.width; x += gridX) {
                if (buffer32[y * canvas.width + x]) {
                    particleAlphabet.particlePositions.push({x: x, y: y});
                }
            }
        }
    },
    animateParticles: function() {
        var p, pPos;
        for (var i = 0, num = particleAlphabet.particles.length; i < num; i++) {
            p = particleAlphabet.particles[i];
            pPos = particleAlphabet.particlePositions[i];
            if (particleAlphabet.particles.indexOf(p) === particleAlphabet.particlePositions.indexOf(pPos)) {
            p.x += (pPos.x - p.x) * .3;
            p.y += (pPos.y - p.y) * .3;
            p.draw(particleAlphabet.ctx);
        }
        }
    },
    animate: function() {
        requestAnimationFrame(particleAlphabet.animate);
        particleAlphabet.ctx.fillStyle = 'rgba(23, 41, 58, .8)';
        particleAlphabet.ctx.fillRect(0, 0, particleAlphabet.W, particleAlphabet.H);
        particleAlphabet.animateParticles();
    }
};

window.onload = particleAlphabet.init;
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Atlas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap + Jquery CDN -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lekton" rel="stylesheet">


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



    <!-- navbar starts here -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Atlas</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">



          <li class="nav-item active">
            <a class="nav-link" href="/pastes/new"> New Paste <span class="sr-only">(current)</span></a>
          </li>

        <% if logged_in? %>
          <li class="nav-item active">
            <a class="nav-link" href="#">Signed in as <%= current_user.username %> <span class="sr-only">(current)</span></a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="/logout"> Log Out <span class="sr-only">(current)</span></a>
          </li>

        <% else %>

            <li class="nav-item active">
            <a class="nav-link" href="/login"> Log In <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item active">
            <a class="nav-link" href="/users/new"> Sign Up <span class="sr-only">(current)</span></a>
            </li>
        <% end %>
        </ul> 

        <!-- search form starts here -->

        <%= form_with url:pastes_path, :class => "form-inline my-2 my-lg-0" ,local:true, method: :get do |form| %>
        <%= text_field_tag :search, "", :class => "form-control mr-sm-2" %>
        <%= submit_tag "Search Pastes", name: nil, :class => "btn btn-outline-success my-2 my-sm-0" %>
        <% end %>
        <!-- search form ends here -->
      </div>
    </nav>
    <!-- navbar ends here -->
    <%= yield %>

    <br>
    <div class="container">
      <div class="row justify-content-md-center">
        <%= link_to "All Pastes", pastes_path, :class => "btn btn-lg btn-primary" %>
      </div>
    </div>
  </body>
</html>

app/views/pastes/_form.html.erb
<div class="container-fluid" >
	<%= form_for @paste, :html => {:class => "form-group"} do |form| %>
		<form>
		  <div class="form-group row">
		  	<div class="col-4">
		    	<label><%= form.label :title %></label>
		    	<div> <%= form.text_field :title, :class => 'form-control'%> </div>
			</div>
		  </div>

		  <div class="form-group row">
		  	<div class = "col-10" id="content">
		    	<label><%= form.label :content %> </label>
		    	<div><%= form.text_area :content, :class => 'form-control' %></div>
		    </div>
		  </div>

		  <%= form.submit :class => 'btn btn-primary' %>
		  <small id="PasteHelp" class="form-text text-muted">If you're not logged in, you will not be able to edit or delete your pastes in the future.</small>

		</form>
	<% end %>
</div>

app/views/pastes/destroy.js.erb
$('#dv<%= @paste.id %>').fadeOut()

app/views/pastes/edit.html.erb
<%= render partial: "form" %>

app/views/pastes/index.html.erb
<br> 
<div class="container-fluid" >
<% @pastes.each do |x| %>

	<div class="card mb-3" id="dv<%=x.id%>">
	  <div class="card-header">
	  	<dl class="row">
		  <dt class=" h2 col-sm-2"> <%= x.title %> <br></dt>
		  	<!-- Show user if available -->
		  	<% if !x.user.nil? %> 
		  	<dd class="col-sm-10 text-right">
		    	<dl class="row">
		      		<dd class="col-sm-10">| by <%= x.user.username %></dd>
		    	</dl>
		    </dd>

		    <% end %>

		</dl>
	  </div>
	  <div class="card-body">
	    <p class="card-text" style = "font-family: 'Lekton', sans-serif;"> <%= x.content.first(500) %></p>
	    <input type="text" style="opacity:0;border:none;" value="<%= x.content.first(500) %>" id="<%=x.id%>" readonly>

	  </div>
	  <div class="card-footer text-muted text-right">
	  	<%= link_to "Click to view more", paste_path(x.id), :class => "text-muted"%>

		<% if logged_in? && current_user.id == x.user_id || logged_in? &&current_user.admin? %>
	  	|
	  	<%= link_to "Edit", edit_paste_path(x.id), :class => "text-muted" %> |
	  	<%= link_to "Delete", paste_path(x.id), method: :delete, data: { confirm: 'Are you sure you want to delete this paste?'}, remote: true, :class => "text-muted"%>

	  	<% end %>

	  	<button class="text-muted" onclick="copyToClipboard(<%=x.id%>)">Copy text</button>
	  </div>
	</div>

<% end %>

</div>

<%= paginate @pastes %>
<%= page_entries_info @pastes %>


<script>
function copyToClipboard(x) {
	console.log("triggered")
  var copyText = document.getElementById(x);
  copyText.select();
  document.execCommand("copy");
  var length = 120;
  if (copyText.value.length > 120){
  	var trimmedString = copyText.value.substring(0, length);
  	alert("Copied the text: " + trimmedString + " ...");
  }
  else{
  	alert("Copied the text: " + copyText.value);
  }
}
</script>

app/views/pastes/new.html.erb
<%= form_with scope: :paste, url: pastes_path, local: true do |form| %>
	<p>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
	</p>


	<p>
		<%= form.label :content %><br>
		<%= form.text_area :content %>
	</p>

	<p>
		<%= form.submit %>
	</p>
<% end %>

app/views/pastes/show.html.erb
<br>
	<div class="card mb-3" id="dv<%=@paste.id%>">
	  <div class="card-header">
	  	<dl class="row">
		  <dt class=" h3 col-sm-2"> <%= @paste.title %> <br></dt>
		  	<!-- Show user if available -->
		  	<% if !@paste.user.nil? %> 
		  	<dd class="col-sm-10 text-right">
		    	<dl class="row">
		      		<dd class="col-sm-10">| by <%= @paste.user.username %></dd>
		    	</dl>
		    </dd>

		    <% end %>

		</dl>
	  </div>
	  <div class="card-body">
	    <p class="card-text" style = "font-family: 'Lekton', sans-serif;"> <%= @paste.content %></p>
	    <input type="text" style="opacity:0;border:none;" value="<%= @paste.content %>" id="clipboard" readonly>
	  </div>
	  <div>
	  	<p class="card-text" style = "font-family: 'Lekton'"> URL: <%= request.original_url %> </p>
	  		  	
	  </div>
	  <div class="card-footer text-muted text-right">


		<% if logged_in? && current_user.id == @paste.user_id || logged_in? &&current_user.admin? %>
	  	<%= link_to "Edit", edit_paste_path(@paste.id), :class => "text-muted" %> |
	  	<%= link_to "Delete", destroyredirect_path(@paste.id), method: :delete, data: { confirm: 'Are you sure you want to delete this paste?'}, :class => "text-muted"%>

	  	<% end %>

	  	<button class="text-muted" onclick="copyToClipboard(<%=@paste.id%>)">Copy text</button>
	  </div>
	</div>



<script>
function copyToClipboard() {
	console.log("here")
  var copyText = document.getElementById("clipboard");
  copyText.select();
  document.execCommand("copy");
  alert("Copied the text: " + copyText.value);
}
</script>

app/views/users/new.html.erb
<div class="container-fluid mx-auto" >
	<h1>Sign up</h1>
		<% if !@user.errors.empty? %>
  			<ul>
   			<% @user.errors.full_messages.each do |message| %>
      			<div class="alert alert-danger">
  					<strong>Error:</strong><li><%= message %></li>
				</div>
      		<% end %>
  			</ul>
		<% end %>

<%= form_with scope: :user, url: users_path, local: true, :html => {:id => "newuser", :class => "form-group"} do |form| %>
		<form>
		  <div class="form-group row">
		  	<div class="col-4">
		    	<label><%= form.label :username %></label>
		    	<%= form.text_field :username, :class => 'form-control' %>
			</div>
		  </div>
		  <br>

		  <div class="form-group row">
		  	<div class="col-4">
		    	<label><%= form.label :email %></label>
		    	<%= form.text_field :email, :class => 'form-control' %>
			</div>
		  </div>

		  <br>
		  <div class="form-group row">
		  	<div class = "col-4">
		    	<label><%= form.label :password %> </label>
		    	<%= form.password_field :password, :class => 'form-control' %>
		    </div>
		  </div>
		  <br>

		  <%= recaptcha_tags %>

		  <br>

		  <%= form.submit :class => 'btn btn-primary' %>
		  
		</form>
	<% end %>
</div>